server:
  port: 8050
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://objective_curran:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: fasdfo3451kb12l3k4h12k5h2lkj5h12lk3b5l12kg61l2k451lk15l43k5h1
  lifetime: 3600000

reportFilesDirectory: ${user.home}/Downloads
